---
- name: restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: apply selinux context
  ansible.builtin.command: restorecon -R '{{ item }}'
  loop:
    - '{{ prometheus_install_dir }}'
    - '{{ prometheus_data_dir }}'
    - '{{ prometheus_config_dir }}'
  changed_when: false
  when: ansible_selinux is defined and ansible_selinux.status == "enabled"

